apiVersion: apps/v1
kind: Deployment
metadata:
  name: attacker
  namespace: l4j-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attacker
  template:
    metadata:
      labels:
        app: attacker
    spec:
      containers:
        - name: attacker
          image: jtb75/my-ubuntu:18.04
          imagePullPolicy: "Always"
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
